const flow = document.querySelector('#flow');
const progressFill = document.querySelector('#progressFill');
const progressText = document.querySelector('#progressText');
const stepLabel = document.querySelector('#stepLabel');
const helpButton = document.querySelector('#helpButton');

let step = 0;
const maxSteps = 9;
const data = { filament: '', purpose: '', process: '0.20 mm', infill: '', walls: '' };
const state = { checks: { prep: [false,false,false,false], slicer: [false,false,false], change: [false,false,false,false] } };
const sliderIcon = `<svg class="slider-icon" viewBox="0 0 64 64" aria-label="Regler" role="img"><path d="M6 12h52M6 27h52M6 42h52M6 57h52"/><circle cx="43" cy="12" r="6"/><circle cx="20" cy="27" r="6"/><circle cx="45" cy="42" r="6"/><circle cx="23" cy="57" r="6"/></svg>`;
const autoOrientIcon = `<svg class="orient-icon" viewBox="0 0 80 70" aria-label="Auto Orient" role="img"><g transform="rotate(45 40 25)"><rect x="24" y="9" width="32" height="32" rx="3"/></g><path d="M33 34l7-17 7 17M36 27h8M14 20v25M14 45l-5-6M14 45l5-6M9 58h62"/></svg>`;
const autoPositionIcon = `<svg class="position-icon" viewBox="0 0 80 70" aria-label="Auto Position" role="img"><g transform="rotate(-6 40 35)"><rect x="10" y="6" width="60" height="56" rx="7"/><rect x="19" y="16" width="24" height="12" rx="6"/><rect x="48" y="14" width="13" height="28" rx="2"/><circle cx="25" cy="37" r="6"/><circle cx="40" cy="37" r="6"/><rect x="19" y="46" width="40" height="10" rx="2"/></g></svg>`;

function updateProgress(label, n) {
  stepLabel.textContent = label; progressText.textContent = `${n} von ${maxSteps}`;
  progressFill.style.width = `${(n / maxSteps) * 100}%`;
}
function button(label, fn, cls='action-button') { return `<button class="${cls}" data-action="${fn}">${label}</button>`; }
function mount(html, label, n=step) { flow.innerHTML = html; updateProgress(label,n); bind(); }
function bind(){
  flow.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',()=>actions[el.dataset.action]?.()));
  flow.querySelectorAll('[data-check]').forEach(el=>el.addEventListener('change',e=>{
    const [group,i] = e.target.dataset.check.split(':'); state.checks[group][+i] = e.target.checked;
    const next = flow.querySelector('#next'); if(next) next.disabled = !state.checks[group].every(Boolean);
  }));
}
const choice = (emoji, title, sub, action, wide='', selected=false) => `<button class="choice ${wide} ${selected?'selected':''}" data-action="${action}"><span class="emoji">${emoji}</span>${title}<small>${sub}</small></button>`;
const check = (group,i,text) => `<label class="check"><input type="checkbox" data-check="${group}:${i}" ${state.checks[group][i]?'checked':''}><span class="check-number">${i + 1}</span><span>${text}</span></label>`;
function start(){ step=0; mount(`<div class="center"><div class="start-icon"><img src="icon.svg?v=6" alt="3D-Drucker"></div><p class="eyebrow">SCHRITT FÜR SCHRITT</p><h2>Was möchtest du machen?</h2><p class="intro">Der Assistent begleitet dich sicher am Creality K1C.</p><div class="choice-grid">${choice('✨','Neuen Druck vorbereiten','Material wählen und Druck starten','filament','wide')}${choice('🔄','Filament wechseln','Alte Rolle heraus, neue Rolle hinein','filamentChange','wide')}</div></div>`,'Start',0); }
function filament(){ step=1; mount(`<p class="eyebrow">SCHRITT 1 · MATERIAL FINDEN</p><h2>Ist das Teil Sonne, Wasser oder Wetter ausgesetzt?</h2><p class="intro">Mit ein paar Fragen finden wir das passende Filament.</p><div class="choice-grid">${choice('☀️','Ja','Zum Beispiel draußen, im Bad oder am Auto','exposureYes')}${choice('🏠','Nein','Das Teil bleibt trocken und drinnen','exposureNo')}${choice('🤷','Ich bin unsicher','Lieber kurz nachfragen','unknown','wide')}</div>${button('← Zurück','start','back')}`,'Material finden',1); }
function outdoorMaterial(){ mount(`<p class="eyebrow">MATERIAL FINDEN</p><h2>Gibt es viel Sonne oder starke Wärme?</h2><p class="intro">Das entscheidet zwischen besonders UV-festem ASA und robustem PETG.</p><div class="choice-grid">${choice('☀️','Ja','Draußen, volle Sonne oder hohe Temperatur','setASA')}${choice('💧','Nein','Vor allem Wasser, aber wenig direkte Sonne','setPETG')}</div>${button('← Zurück','filament','back')}`,'Material finden',1); }
function indoorMaterial(){ mount(`<p class="eyebrow">MATERIAL FINDEN</p><h2>Muss das Teil flexibel sein?</h2><p class="intro">Zum Beispiel ein Puffer, Fuß oder ein biegsames Teil.</p><div class="choice-grid">${choice('🧸','Ja, flexibel','Weich, biegsam und stoßfest','setTPU')}${choice('✨','Nein, fest','Deko, Figuren und normale Innenteile','setPLA')}</div>${button('← Zurück','filament','back')}`,'Material finden',1); }
function purpose(){ step=2; mount(`<p class="eyebrow">SCHRITT 2 · VERWENDUNGSZWECK</p><h2>Wofür ist das Teil?</h2><p class="intro">Danach zeigt dir die App automatisch die passenden Slicer-Einstellungen.</p><div class="choice-grid">${choice('✨','Deko & Figuren','Leicht · wenig Material · nicht stark belastet','purposeLight')}${choice('🔧','Alltag & Funktion','Die beste Standardwahl für die meisten Teile','purposeStandard')}${choice('💪','Stark belastet','Robust für Halterungen und Nutzteile','purposeStrong','wide')}</div>${button('← Material ändern','filament','back')}`,'Verwendungszweck',2); }
function materialSelected(){ const descriptions={PLA:'PLA ist ideal für Deko, Figuren und normale Teile für drinnen.',PETG:'PETG ist robust und gut für Teile mit Wasser- oder Wetterkontakt.',TPU:'TPU ist flexibel, biegsam und stoßfest.',ASA:'ASA ist besonders gut für sonnige, warme und wetterfeste Außenteile.'}; mount(`<div class="center"><div class="start-icon">✓</div><p class="eyebrow">MATERIAL AUSGEWÄHLT</p><h2>${data.filament} ist ausgewählt</h2><p class="intro">${descriptions[data.filament]}</p>${button('Weiter zum Drucker vorbereiten →','preparation')}${button('← Filament ändern','filament','back')}</div>`,'Filament ausgewählt',2); }
function preparation(){ step=3; const drying={PLA:'PLA: ca. 1–2 Stunden bei 45–50 °C',PETG:'PETG: ca. 2–4 Stunden bei 60–65 °C',TPU:'TPU: ca. 3–4 Stunden bei 50–55 °C',ASA:'ASA: ca. 4–6 Stunden bei 70–80 °C'}[data.filament]; mount(`<p class="eyebrow">SCHRITT 3 · VORBEREITEN</p><h2>Ist der Drucker bereit?</h2><p class="intro">Bitte alle Punkte abhaken.</p><div class="notice yellow"><span class="notice-icon">☀️</span><div><b>Trocknungs-Richtwert für ${data.filament}</b>${drying}.</div></div><div class="notice green"><span class="notice-icon">🧴</span><div><b>Kleber dünn auftragen</b>Etwas Kleber aufs saubere Druckbett geben und dünn, gleichmäßig verwischen. So entstehen keine Kleber-Blobs unter dem Druck.</div></div><div class="checks">${check('prep',0,'Filament ist trocken')}${check('prep',1,'Richtige Rolle ist eingelegt')}${check('prep',2,'Druckbett ist sauber')}${check('prep',3,'Kleber ist dünn und gleichmäßig verwischt')}</div><button id="next" class="action-button" data-action="orca" ${state.checks.prep.every(Boolean)?'':'disabled'}>Weiter zu Orca Slicer</button>${button('← Zweck ändern','purpose','back')}`,'Drucker vorbereiten',3); }
function filamentChange(){ step=0; mount(`<p class="eyebrow">FILAMENT WECHSELN</p><h2>Neue Rolle einlegen</h2><p class="intro">Alles dafür machst du direkt am Display des K1C.</p><div class="notice green"><span class="notice-icon">🌡️</span><div><b>Temperatur für Rückziehen &amp; Extrudieren</b>PLA/TPU: ca. 220 °C · PETG: ca. 240 °C · ASA: ca. 260 °C</div></div><div class="checks">${check('change',0,`Tab ${sliderIcon} am Drucker auswählen`)}${check('change',1,'Richtige Temperatur für das alte Filament einstellen und abwarten')}${check('change',2,'Am Display „Rückziehen“ drücken und altes Filament vorsichtig herausnehmen')}${check('change',3,'Neue Rolle einlegen, Temperatur für das neue Filament einstellen und erst dann „Extrudieren“ drücken')}</div><div class="notice yellow"><span class="notice-icon">⚠️</span><div><b>Bei Widerstand: stoppen</b>Nicht mit Gewalt ziehen oder schieben. Wenn das Filament klemmt, bitte Samuel fragen.</div></div>${button('Fertig – zurück zum Start','start')}${button('← Zurück','start','back')}`,'Filament wechseln',0); }
function orca(){ step=4; mount(`<p class="eyebrow">SCHRITT 4 · ORCA SLICER</p><h2>Alle Einstellungen einstellen</h2><p class="intro">Öffne Orca Slicer. Die Einstellungen unten passen zu <strong>${data.filament}</strong> und <strong>${data.purpose}</strong>.</p><div class="orca-settings"><div><span>1</span><p><b>Printer</b><strong>K1C 0.4mm KAMP</strong></p></div><div><span>2</span><p><b>Nozzle</b><strong>0.4 · Brass</strong></p></div><div><span>3</span><p><b>Filament</b><strong>Passendes ${data.filament}-Profil wählen</strong></p></div><div><span>4</span><p><b>Process</b><strong>0.20 mm</strong></p></div><div><span>5</span><p><b>Füllung</b><strong>${data.infill} %</strong></p></div><div><span>6</span><p><b>Außenwände</b><strong>${data.walls} Wände</strong></p></div></div><div class="notice green"><span class="notice-icon">📁</span><div><b>Dann Modell importieren</b>Datei hineinziehen oder <strong>Datei → Importieren</strong> wählen.</div></div>${button('Einstellungen fertig & Modell importiert →','autoOrient')}${button('← Zurück','preparation','back')}`,'Slicer einstellen',4); }
function autoOrient(){ step=5; mount(`<p class="eyebrow">SCHRITT 5 · ORCA SLICER</p><h2 class="with-step-icon">${autoOrientIcon}Auto Orient anwenden</h2><p class="intro">Klicke auf das Modell und anschließend auf <strong>Auto Orient</strong>. Orca Slicer findet eine gute Druckausrichtung.</p>${button('Auto Orient ist fertig →','autoPosition')}${button('← Zurück','orca','back')}`,'Auto Orient',5); }
function autoPosition(){ step=6; mount(`<p class="eyebrow">SCHRITT 6 · ORCA SLICER</p><h2 class="with-step-icon">${autoPositionIcon}Auto Position anwenden</h2><p class="intro">Klicke auf <strong>Auto Position</strong>. Das Modell wird passend auf dem Druckbett platziert.</p>${button('Auto Position ist fertig →','slicer')}${button('← Zurück','autoOrient','back')}`,'Auto Position',6); }
function preheat(){ step=6; mount(`<p class="eyebrow">SCHRITT 6 · PROFIL</p><h2>Mit Vorheizen drucken?</h2><p class="intro">Das Vorheizen sorgt meist für eine zuverlässigere erste Schicht.</p><div class="choice-grid">${choice('🔥','Vorheizen','Empfohlen · Bett und Düse auf Temperatur bringen','preheatYes')}${choice('⏩','Ohne Vorheizen','Nur wenn Drucker und Bett bereits warm sind','preheatNo')}</div>${button('← Zurück','autoPosition','back')}`,'Vorheizen wählen',6); }
function profile(){ step=7; mount(`<p class="eyebrow">SCHRITT 7 · DRUCKPROFIL</p><h2>Wie soll das Teil werden?</h2><p class="intro">Wähle die Füllung. Für die meisten Teile reichen kleine Werte völlig aus.</p><div class="choice-grid">${choice('◌','8 % Füllung','Sehr leicht · Deko, Figuren und Modelle','infill8','',data.infill==='8 %')}${choice('◒','15 % Füllung','Standard · stabil genug für viele Teile','infill15','',data.infill==='15 %')}${choice('◕','30 % Füllung','Maximal · für belastete, funktionale Teile','infill30','',data.infill==='30 %')}${choice('💪','Extra stabil','5 statt 3 Außenwände · stärkere Hülle für belastete Teile','strengthHigh','wide',data.strength==='Extra stabil')}</div>${button('Weiter zu Slice Plate','slicer')}${button('← Zurück','preheat','back')}`,'Profil auswählen',7); }
function slicer(){ step=7; mount(`<p class="eyebrow">SCHRITT 7 · ORCA SLICER</p><h2>„Slice Plate“ klicken</h2><p class="intro">Prüfe kurz die Einstellungen und klicke dann oben rechts auf <strong>Slice Plate</strong>.</p><div class="checks">${check('slicer',0,'Die richtige Datei ist ausgewählt')}${check('slicer',1,`Profil: K1C · ${data.filament} · ${data.process} · ${data.infill} % · ${data.walls} Wände`)}${check('slicer',2,'Slice Plate wurde angeklickt und die Vorschau sieht gut aus')}</div><button id="next" class="action-button" data-action="startPrint" ${state.checks.slicer.every(Boolean)?'':'disabled'}>Weiter zu Print →</button>${button('← Slicer-Einstellungen ändern','orca','back')}`,'Slice Plate',7); }
function startPrint(){ step=8; mount(`<p class="eyebrow">SCHRITT 8 · ORCA SLICER</p><h2>Jetzt „Print“ klicken</h2><p class="intro">Wenn die Vorschau gut aussieht, klicke auf <strong>Print</strong> und sende die Datei an den K1C.</p><div class="notice green"><span class="notice-icon">✓</span><div><b>Du bist vorbereitet</b>Bleib beim Start kurz in der Nähe – besonders für die erste Schicht.</div></div>${button('Der Druck läuft – erste Schicht prüfen','firstLayer')}${button('← Zurück','slicer','back')}`,'Print',8); }
function firstLayer(){ step=9; mount(`<p class="eyebrow">SCHRITT 9 · ERSTE SCHICHT</p><h2>Sieht die erste Schicht gut aus?</h2><p class="intro">Das Filament sollte gleichmäßig haften und nicht am Druckkopf mitfahren.</p><div class="choice-grid">${choice('✅','Ja, sieht gut aus','Weiterlaufen lassen und später nochmal schauen','success','wide')}${choice('⚠️','Nein oder unsicher','Problemhilfe öffnen','problems','wide')}</div>${button('← Zurück','startPrint','back')}`,'Erste Schicht prüfen',9); }
function unknownFilament(){ mount(`<div class="notice yellow"><span class="notice-icon">⚠️</span><div><b>Gelb · bitte kurz nachfragen</b>Bitte den Druck noch nicht starten. Mach ein Foto vom Etikett der Rolle und schick es Samuel.</div></div><h2>Wir finden das schnell heraus.</h2><p class="intro">Sobald klar ist, ob es PLA, PETG, TPU oder ASA ist, kannst du hier wieder von vorn beginnen.</p>${button('Zurück zum Start','start')}`,'Material prüfen',1); }
function problems(){ mount(`<div class="problem-title"><span>🛑</span><div><p class="eyebrow">PROBLEMHILFE</p><h2>Was ist passiert?</h2></div></div><p class="intro">Wenn du unsicher bist, wähle lieber „Ungewöhnliches Verhalten“.</p><div class="choice-grid problem-card">${choice('⬇️','Schlechte Haftung','Teil löst sich oder fährt mit','adhesion','wide')}${choice('🔊','Komische Geräusche','Kratzen, Knacken oder Rattern','noise','wide')}${choice('🧵','Filamentproblem','Es kommt nichts oder nur Fäden','filamentIssue','wide')}${choice('❗','Ungewöhnliches Verhalten','Rauch, Geruch, Kollision oder ich weiß es nicht','unsafe','wide')}</div>${button('← Zum Druck zurück','firstLayer','back')}`,'Problemhilfe',step); }
function problemResult(kind){ const content={ adhesion:['Gelb','⚠️','Druck anhalten und kurz nachfragen','Wenn sich das Teil löst oder verschiebt: Druck stoppen. Bitte ein Foto machen und Samuel schicken. Nicht während des Drucks am Druckbett ziehen.','yellow'],noise:['Rot','🛑','Bitte sofort stoppen','Bei Kratzen, Rattern oder einem Zusammenstoß: Druck abbrechen. Nichts am Drucker auseinanderbauen. Foto oder kurzes Video an Samuel schicken.','red'],filamentIssue:['Gelb','🧵','Druck pausieren und nachfragen','Wenn kein Material herauskommt: Druck pausieren. Bitte nicht mit Werkzeugen im Druckkopf stochern. Foto an Samuel schicken.','yellow'],unsafe:['Rot','🛑','Bitte sofort stoppen','Bei Rauch, Brandgeruch, starker Hitze oder einer Kollision: Drucker stoppen und ausschalten. Danach Samuel informieren.','red']}[kind]; mount(`<div class="notice ${content[4]}"><span class="notice-icon">${content[1]}</span><div><b>${content[0]} · ${content[2]}</b>${content[3]}</div></div><h2>Du machst das richtig.</h2><p class="intro">Im Zweifel lieber stoppen – ein abgebrochener Druck ist leichter zu lösen als ein beschädigter Drucker.</p>${button('Problemhilfe schließen','firstLayer')}${button('Anderes Problem auswählen','problems','back')}`,'Problemhilfe',step); }
function success(){ mount(`<div class="center"><div class="start-icon">🎉</div><p class="eyebrow">ALLES GUT</p><h2>Die erste Schicht hält!</h2><p class="intro">Lass den Druck weiterlaufen. Schau nach etwa 10 Minuten und vor dem Ende noch einmal kurz nach.</p>${button('Fertig – zurück zum Start','start')}</div>`,'Erste Schicht geprüft',9); }
const actions={start,filament,filamentChange,exposureYes:outdoorMaterial,exposureNo:indoorMaterial,outdoorMaterial,indoorMaterial,setPLA:()=>{data.filament='PLA';purpose()},setPETG:()=>{data.filament='PETG';purpose()},setTPU:()=>{data.filament='TPU';purpose()},setASA:()=>{data.filament='ASA';purpose()},purpose,purposeLight:()=>{data.purpose='Deko & Figuren';data.infill='8';data.walls='3';materialSelected()},purposeStandard:()=>{data.purpose='Alltag & Funktion';data.infill='15';data.walls='3';materialSelected()},purposeStrong:()=>{data.purpose='Stark belastet';data.infill='30';data.walls='5';materialSelected()},unknown:unknownFilament,materialSelected,preparation,orca,autoOrient,autoPosition,preheat,preheatYes:()=>{data.preheat='Vorheizen';profile()},preheatNo:()=>{data.preheat='Ohne Vorheizen';profile()},profile,infill8:()=>{data.infill='8';profile()},infill15:()=>{data.infill='15';profile()},infill30:()=>{data.infill='30';profile()},strengthHigh:()=>{data.walls=data.walls==='5'?'3':'5';profile()},slicer,startPrint,firstLayer,problems,adhesion:()=>problemResult('adhesion'),noise:()=>problemResult('noise'),filamentIssue:()=>problemResult('filamentIssue'),unsafe:()=>problemResult('unsafe'),success};
helpButton.addEventListener('click',problems); start();

